---
name: Update
on:
  workflow_dispatch: null
  schedule:
    - cron: 0 19 * * *
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Installing requirements
        run: |
          pip install -r requirements.txt 
      - name: Building UnityPack
        run: |
          python setup.py build
      - name: Installing UnityPack
        run: |
          python setup.py install --user
      - name: Retrieving models
        run: |
          python ./py/get_models.py
      - name: Generating models.json
        run: |
          python ./py/generate_models.py
      - name: Generating audio.json
        run: |
          python ./py/generate_audio.py
      - name: Create Commit
        run: |
          git add .
          git config --global user.email "bot@github.com"
          git config --global user.name "Github Bot"
          git commit -m "[Update] $(cat ./data/version.txt)"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: update
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "[Update] $(cat ./data/version.txt)" --body "$(cat ./data/version.txt)" --head update
